Step number 2 is here
Georg1703/django-learn pull request #13
Opened 2024-09-04 10:37 UTC by tudor1703

2024-09-04 11:31 UTC, tudor1703 commented
The second commit is from step 3, I forgot to change branches.

2024-09-04 18:01 UTC, Georg1703 requested changes
Will be nice to see file env_example where will be names of variables that i should setup in .env so the project will start successfully.

db should never get to github, sqlite is also a mini database so exclude it from git.

2024-09-07 12:16 UTC, Georg1703 requested changes

2024-09-07 12:16 UTC, Georg1703 commented on mysite/mysite/settings.py
> +        'NAME': os.path.join(BASE_DIR, os.getenv('DATABASE_PATH')),
De ce ai schimbat asta aici dar in .env example nu ai inclus DATABASE_PATH ?

2024-09-07 12:16 UTC, Georg1703 commented on mysite/mysite/settings.py
> +        'NAME': os.path.join(BASE_DIR, os.getenv('DATABASE_PATH')),
Eu as zice ca nu e nevoie de asta aici si nici de datele legate de database in env example, oricum sqlite nu e o baza de date adevarata, o sa facem asta pe urma.

2024-09-09 03:43 UTC, Georg1703 requested changes

2024-09-09 03:43 UTC, Georg1703 commented on mysite/mysite/settings.py
> +        'NAME': BASE_DIR / 'db.sqlite3',
De ce ai schimbat asta ? Doar ai adaugat DATABASE_PATH in env.

2024-09-16 17:02 UTC, merged